### PR TITLE
Profile Repository Unit Test

### LINKED ISSUE #53: Test Cases
Placeholder for project part 3 submission to remind us to have test cases (UI, unit, integration)

Write runnable tests for your model and control classes. Provide intent tests for the requirements you have done. Deliver the test code to your source repository. If you have test data files, also include those. Test data should be realistic.

### LINKED ISSUE #77: Add unit tests for ViewModels and Repositories
Use Mockito or Firebase emulator to add automated tests in CI

- Test FirebaseAuth
- Test LibraryViewModel, UnlibraryViewModel, and RepositoryViewModel

### PR DESCRIPTION
**Pull request by cyrusdiego**
# Summary
- Added unit test for profile repository
- I could not mock the firebase auth properly so I couldn't test updated the user information, if anyone has any suggestions please let me know. The main issue is mocking the `Task<Void>` that `FiremAuth.getCurrentUser().updateEmail(...)` returns and setting the `.addOnCompleteListener` 

Closes #53 
Closes #77

### CODE REVIEW

**Review by calebschoepp — DISMISSED** [review]
Yep LGTM. You've confirmed that the profile is still working with the change to use `mAuth`?

**Review by armiantos — DISMISSED** [review]
LGTM, given the amount of time we have left, I believe this is the best we can do. Awesome job!

If i were to nit I'd go with making @Before to @BeforeClass so its only called once and user will persist in future tests

**Comment by cyrusdiego** [comment]
@calebschoepp yep the profile is still working with mAuth

**Comment by cyrusdiego** [comment]
@armiantos changed to `@beforeclass`

**Review by armiantos — APPROVED** [review]
LGTM!

**Pull request merged**
