### PR TITLE
Add Firebase configuration and CI/CD

### PR DESCRIPTION
**Pull request by calebschoepp**
## Changes
- Add `google-services.json`
- Add Firebase to gradle
- Add Firebase to CI/CD

@CMPUT301F20T24/team-24

### CODE REVIEW

**Review by cyrusdiego — APPROVED** [review]
LGTM!

**Comment by armiantos** [comment]
Wait is this not work in progress?

**Comment by calebschoepp** [comment]
Yeah it is WIP, still working on getting the CI/CD working.

**Comment by calebschoepp** [comment]
Alright, looking for a review now -- no longer WIP. The instrumented tests are working :). They're kind of slow though and I think we only get a limited amount for free so I'll probably post a follow-up PR that only runs instrumented tests on merges to master, not on every PR.

**Review by armiantos — APPROVED** [review]
Looks good now. Thank you for doing this Caleb!

**Review by cyrusdiego — APPROVED** [review]

**Pull request merged**
